// NEXT
import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>UI Lab - Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1 className="text-6xl">Home</h1>
      </main>
    </>
  );
};

export default Home;
