import {} from "react";
// COMP
// NEXT
import Head from "next/head";
// MUI
// ICONS

const TypographyPage = () => {
  return (
    <>
      <Head>
        <title>UI Lab - Typography</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1>Heading 1</h1>
        <h2>Heading 2</h2>
        <h3>Heading 3</h3>
        <h4>Heading 4</h4>
        <p>
          Lorem, ipsum dolor sit amet <span>consectetur</span> adipisicing elit.
          Provident placeat omnis veniam dolores ducimus explicabo expedita{" "}
          <b>expedita</b> molestias adipisci, unde, voluptas fuga{" "}
          <i>distinctio</i> ab error voluptatem nesciunt eligendi corporis.
          Veniam.
        </p>
      </main>
    </>
  );
};

export default TypographyPage;
